#!/usr/bin/env bash
#
# vendor-standards.sh — re-copy vendored standards from their canonical
# home in MDC-Master-Planning into docs/standards/.
#
# Governed by Documentation Standard § "Cross-ecosystem vendored standards —
# mirror/fork provenance (binding)": a separate-ecosystem repo COPIES a standard
# in rather than live-referencing it, and every copy carries a provenance +
# INTENT flag (MIRROR or FORK). All copies here are MIRROR.
#
# WHY VENDOR RATHER THAN REFERENCE: claude-dot-files deploys standalone to
# workstations and VMs that may not have mdc-master-planning checked out, and a
# standard you cannot read is not binding. Vendoring makes it readable
# everywhere.
#
# WHY VERBATIM, AND WHY YOU MUST NOT EDIT THE COPIES: the alternative to a
# reference is a FORK, and a fork drifts silently — two repos with the same
# section numbers saying different things is worse than not having the file at
# all. Local edits are therefore forbidden. Amendments go upstream, then
# re-vendor with this script. `--check` fails if a copy has drifted, so the
# drift is loud rather than discovered months later.
#
# WHAT BELONGS LOCALLY INSTEAD:
#   docs/standards/temporal/README.md                     applicability — what binds now vs at port time
#   docs/standards/temporal/claude-dot-files-addendum.md  rules that are genuinely OURS
#
# Usage:
#   scripts/helpers/vendor-standards.sh            re-vendor from source
#   scripts/helpers/vendor-standards.sh --check    verify no local drift (exit 1 if drifted)

set -euo pipefail

# source-subpath:dest-name — add a line to vendor another standard
FILES=(
  "development/temporal/temporal_standard.md:temporal/temporal_standard.md"
  "development/temporal/worker_deployment_standard.md:temporal/worker_deployment_standard.md"
  "development/temporal/stateful_patterns.md:temporal/stateful_patterns.md"
  "documentation/documentation_standard.md:documentation/documentation_standard.md"
  "development/research/research_standard.md:research/research_standard.md"
  "development/testing/testing_standard.md:testing/testing_standard.md"
)
DEST="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/docs/standards"

# The canonical repo lives in different places on workstations vs VMs.
SRC=""
for candidate in "$HOME/Repos/mdc-master-planning" /opt/skyy-net/mdc-master-planning; do
    if [[ -d "$candidate/standards/development/temporal" ]]; then SRC="$candidate"; break; fi
done
if [[ -z "$SRC" ]]; then
    echo "Error: mdc-master-planning not found in ~/Repos or /opt/skyy-net." >&2
    echo "       Clone it, or pass its path as \$1." >&2
    [[ -n "${1:-}" && -d "${1}/standards/development/temporal" ]] && SRC="$1" || exit 1
fi
SRC_DIR="${SRC}/standards"

CHECK_ONLY=false
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=true

SHA=$(git -C "$SRC" rev-parse HEAD)
DATE=$(git -C "$SRC" log -1 --format=%ad --date=short)
fail=0

for entry in "${FILES[@]}"; do
    src="${SRC_DIR}/${entry%%:*}"
    dst="${DEST}/${entry##*:}"
    f="$(basename "${entry##*:}")"
    mkdir -p "$(dirname "$dst")"
    [[ -f "$src" ]] || { echo "Error: missing upstream file: $src" >&2; exit 1; }

    if $CHECK_ONLY; then
        # Compare only the body — the header carries provenance and is ours.
        n=$(grep -n '^---$' "$dst" | head -1 | cut -d: -f1)
        if [[ -z "$n" ]] || ! diff -q <(tail -n +$((n + 2)) "$dst") "$src" >/dev/null; then
            echo "✗ ${entry##*:} has DRIFTED from upstream (or was edited locally)"
            fail=1
        fi
        continue
    fi

    {
        printf '<!-- VENDORED — DO NOT EDIT LOCALLY -->\n'
        printf '> *Vendored from `helloskyy-io/MDC-Master-Planning` · `standards/%s` on %s (`%s`).*\n' "${entry%%:*}" "$DATE" "${SHA:0:7}"
        printf '> *Intent: **MIRROR** — this copy is meant to track the source. A general improvement made here is retrofitted upstream in the same work; anything specific to this ecosystem does not belong in this file at all.*\n>\n'
        printf '> Per Documentation Standard § *Cross-ecosystem vendored standards (binding)*. **Do not edit this file.** Amendments go upstream, then re-vendor.\n'
        printf '> Ecosystem-specific content belongs in the sibling `README.md` (applicability) or an `*-addendum.md`.\n>\n'
        printf '> Re-vendor with: `scripts/helpers/vendor-standards.sh`\n\n---\n\n'
        cat "$src"
    } > "$dst"
    echo "✓ vendored ${entry##*:}"
done

if $CHECK_ONLY; then
    [[ $fail -eq 0 ]] && echo "✓ all vendored standards match upstream ${SHA:0:7}"
    exit $fail
fi

echo
echo "Vendored from ${SRC} @ ${SHA:0:7} (${DATE})"
echo "Review the diff before committing — an upstream change may invalidate something built here."
